// STYLES
import "./globals.scss";
import "../public/font-icons/icons.css";

import type { Metadata } from "next";
import clsx from "clsx";

// PLUGINS
import { inter, poppins, bricolageGrotesque } from "@/plugins";

import { FloatingNav } from "@/components/ui";

// CONSTANTS
import { NavItems } from "@/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // metadataBase: new URL(baseUrl),
  // title: {
  //   default: 'Next.js Portfolio Starter',
  //   template: '%s | Next.js Portfolio Starter',
  // },
  // description: 'This is my portfolio.',
  // openGraph: {
  //   title: 'My Portfolio',
  //   description: 'This is my portfolio.',
  //   url: baseUrl,
  //   siteName: 'My Portfolio',
  //   locale: 'en_US',
  //   type: 'website',
  // },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx(
        bricolageGrotesque.variable,
        inter.variable,
        poppins.variable,
        "scroll-smooth overflow-y-auto overflow-x-hidden"
      )}
    >
      <body className="antialiased w-full min-h-screen flex flex-col items-center bg-background">
        <FloatingNav navItems={NavItems} />

        {children}
      </body>
    </html>
  );
}
